import { Injectable, inject } from '@angular/core';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { PdfViewerDialogComponent } from '../../shared/components/pdf-viewer-dialog/pdf-viewer-dialog';
import { ApiClientService } from '../api/api-client.service';

export type PrescriptionPdfReferralType = 'none' | 'standard' | 'extended';

export interface PrescriptionPdfOptions {
  referralType: PrescriptionPdfReferralType;
  doctorName?: string;
  treatmentDetail?: string;
}

export interface FinanceFormPdfParams {
  startDate: string;
  endDate: string;
  doctorId: number;
  paymentMethod: string;
}

/**
 * PdfService — handles downloading/opening PDF documents generated by Forge.
 *
 * Endpoints:
 *  - POST /patients/{patientId}/prescriptions/{id}/pdf?referralType=... — Prescription PDF
 *  - POST /patients/{patientId}/payments/{id}/pdf                         — Receipt PDF
 *  - GET /finances/form?...                                              — Form 25 report PDF
 *  - GET /finances/form/summary?...                                      — Form 25 summary PDF
 */
@Injectable({
  providedIn: 'root'
})
export class PdfService {
  private dialog = inject(MatDialog);
  private apiClient = inject(ApiClientService);

  /**
   * Opens a prescription PDF in the embedded viewer.
   * @param patientId Patient database ID
   * @param prescriptionId Prescription database ID
   * @param options Referral type and optional print details body
   */
  openPrescriptionPdf(
    patientId: number,
    prescriptionId: number,
    options: PrescriptionPdfOptions = { referralType: 'none' },
  ): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getPrescriptionPdfUrl(patientId, prescriptionId, options.referralType);
    const body = {
      doctorName: options.doctorName ?? '',
      treatmentDetail: options.treatmentDetail ?? '',
    };

    return this.openPdf(url, `prescription-${prescriptionId}.pdf`, false, undefined, {
      method: 'POST',
      body,
    });
  }

  /**
   * Opens a receipt PDF in the embedded viewer.
   * @param patientId Patient database ID
   * @param id Receipt database ID
   */
  openReceiptPdf(patientId: number, id: number): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getReceiptPdfUrl(patientId, id);
    return this.openPdf(url, `receipt-${id}.pdf`, false);
  }

  /**
   * Opens a patient details PDF in the embedded viewer.
   * @param patientId Patient database ID
   * @param fileId Patient file record ID (for delete option)
   */
  openPatientPdf(patientId: number, fileId: number): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getPatientPdfUrl(patientId);
    return this.openPdf(url, `patient-${patientId}.pdf`, true, fileId);
  }

  /**
   * Opens the Form 25 report PDF for the given finance filters.
   */
  openFinanceForm25Pdf(params: FinanceFormPdfParams): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getFinanceForm25PdfUrl(params);
    return this.openPdf(url, `form25-${params.startDate}-to-${params.endDate}.pdf`, false);
  }

  /**
   * Opens the Form 25 summary PDF for the given finance filters.
   */
  openFinanceForm25SummaryPdf(
    params: FinanceFormPdfParams,
  ): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getFinanceForm25SummaryPdfUrl(params);
    return this.openPdf(url, `form25-summary-${params.startDate}-to-${params.endDate}.pdf`, false);
  }

  private openPdf(
    url: string,
    filename: string,
    isPatientPdf: boolean,
    fileId?: number,
    request?: { method?: 'GET' | 'POST'; body?: unknown },
  ): MatDialogRef<PdfViewerDialogComponent, any> {
    return this.dialog.open(PdfViewerDialogComponent, {
      width: '85vw',
      maxWidth: '1200px',
      data: {
        pdfUrl: url,
        filename,
        isPatientPdf,
        fileId,
        method: request?.method,
        body: request?.body,
      },
      panelClass: 'pdf-viewer-dialog-panel'
    });
  }
}
