import { Injectable, inject } from '@angular/core';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { PdfViewerDialogComponent } from '../../shared/components/pdf-viewer-dialog/pdf-viewer-dialog';
import { ApiClientService } from '../api/api-client.service';

/**
 * PdfService — handles downloading/opening PDF documents generated by Forge.
 *
 * Three endpoints are exposed:
 *  - GET /prescriptions/{id}/pdf          — Prescription print-fill PDF
 *  - GET /finance/recipts/{id}/pdf        — Receipt PDF
 *  - GET /finance/form3c/pdf?fromDate=&toDate=[&doctorId=]  — Form 3C report PDF
 */
@Injectable({
  providedIn: 'root'
})
export class PdfService {
  private dialog = inject(MatDialog);
  private apiClient = inject(ApiClientService);

  /**
   * Opens a prescription PDF in the embedded viewer.
   * @param id Prescription database ID
   */
  openPrescriptionPdf(patientId: number, prescriptionId: number): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getPrescriptionPdfUrl(patientId, prescriptionId);
    return this.openPdf(url, `prescription-${prescriptionId}.pdf`, false);
  }

  /**
   * Opens a receipt PDF in the embedded viewer.
   * @param id Receipt database ID
   */
  openReceiptPdf(id: number): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getReceiptPdfUrl(id);
    return this.openPdf(url, `receipt-${id}.pdf`, false);
  }

  /**
   * Opens a patient details PDF in the embedded viewer.
   * @param patientId Patient database ID
   * @param fileId Patient file record ID (for delete option)
   */
  openPatientPdf(patientId: number, fileId: number): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getPatientPdfUrl(patientId);
    return this.openPdf(url, `patient-${patientId}.pdf`, true, fileId);
  }

  /**
   * Downloads/Opens the Form 3C dental patient register as a PDF in the embedded viewer.
   * @param fromDate Start date in YYYY-MM-DD format
   * @param toDate End date in YYYY-MM-DD format
   * @param doctorId Optional doctor ID to scope the report to a single doctor
   */
  downloadForm3C(fromDate: string, toDate: string, doctorId?: number): MatDialogRef<PdfViewerDialogComponent, any> {
    const url = this.apiClient.getForm3CPdfUrl(fromDate, toDate, doctorId);
    return this.openPdf(url, `form3c-${fromDate}-to-${toDate}.pdf`, false);
  }

  private openPdf(
    url: string,
    filename: string,
    isPatientPdf: boolean,
    fileId?: number
  ): MatDialogRef<PdfViewerDialogComponent, any> {
    return this.dialog.open(PdfViewerDialogComponent, {
      width: '85vw',
      maxWidth: '1200px',
      data: {
        pdfUrl: url,
        filename,
        isPatientPdf,
        fileId
      },
      panelClass: 'pdf-viewer-dialog-panel'
    });
  }
}
